// Generated by CoffeeScript 1.3.3
(function() {
  var $;

  $ = jQuery;

  $.fn.jFixed = function(opt) {
    var default_options, options;
    default_options = {
      position: "top",
      animationSpeed: 300
    };
    options = $.extend({}, default_options, opt);
    this.each(function() {
      var $_that;
      $_that = $(this);
      $_that.scrollTop = $(window).scrollTop();
      $_that.isVisible = $_that.is(":visible");
      $_that.selfHeight = $_that.height();
      if (options.position === "bottom") {
        $_that.css("bottom", "0");
      }
      setInterval(function() {
        var currentScrollTop, t;
        currentScrollTop = $(window).scrollTop();
        $_that.isVisible = $_that.is(":visible");
        if ($_that.scrollTop !== currentScrollTop) {
          if ($_that.isVisible) {
            $_that.stop(true, true).animate({
              opacity: "toggle"
            }, options.animationSpeed);
          }
        } else {
          t = currentScrollTop;
          if (options.position === "bottom") {
            t = currentScrollTop + $(window).height() - $_that.selfHeight;
            $_that.css("bottom", "" + (-1 * currentScrollTop) + "px");
          }
          $_that.css("top", "" + t + "px");
          if (!$_that.isVisible) {
            $_that.stop(true, true).animate({
              opacity: "toggle"
            }, options.animationSpeed);
          }
        }
        return $_that.scrollTop = currentScrollTop;
      }, 500);
    });
    return this;
  };

}).call(this);
